### ISSUE TITLE
h1,h2,h3 support for <Title>

### ISSUE THREAD

**Issue by kennetvu** [alexanbj/rulma#7]
Current implementation of `Title`-component render a `<p>`tag.. 
Should we support `h1`,`h2`,`h3` etc... to be semantically correct? 

And how should the API look like ? 

we can extend the `<Title>` component with a new prop: header
e.g: `<Title level="2" header>Generates h2</Title>`, and defaultProps for header is false, which will render `<p>`tag

or we can create new components for title, e.g `<Title.H1>Title 1</Title.H1>` and `<Title.H2>Title 2</Title.H2>` ? (looks ugly tbh)

or we can let the user decide which tag he wants to use but then we probably need to hack the component with `cloneElement` and add classnames to children component. e.g: `<Title><p>something</p></Title>` and it generates `<p class="title is-3">something</p>` (the api looks ugly) 

comments @alexanbj ?

**Comment by alexanbj** [comment]
I agree that the last approach, with cloneElement, is something we can discard right away.

How about creating a component for each of the header elements? The usage would look something like:
```jsx
<H1>Title</H1>
<H3 subtitle>Subtitle</H3>
```

Though I guess it would be cumbersome to import multiple components for each header type instead of a single component as it is now.

It also introduces another problem. Should we support both `<Title />` and `<H1-6/>`? Where one renders paragraphs and the other actual header elements? That also feels a bit weird. Even though they are semantically very different, they would look the same to the user.

**Comment by alexanbj** [comment]
So after thinking about it some more. I really didn't want several ways to render titles/subtitles. Both components now render header tags by default. So `<Title size="4" />` will render as `<h4 />`. I guess I feel header tags feel like more semantically correct HTML than paragraph tags.

If you really want the title or subtitle to render as something else, such as a span, p or div, I added the ability to supply tag as a prop. For instance, `<Title size="4" tag="p" />`. 

What do you think, @kennetvu ?

**Comment by kennetvu** [comment]
It sounds great! I like what you have done with Title!
